### ISSUE TITLE
Compilation Error - Ubuntu 12.04

### ISSUE THREAD

**Issue by nuggetbram** [bonesoul/CoiniumServ#303]
I'm getting this error after trying to compile on Ubuntu 12.04 - on two VPS's.

http://pastebin.com/pnRevRhm
